# Site settings
title: Anarghya Das
email: anarghya@buffalo.edu
description: Academic webpage of Anarghya Das
baseurl: "/~anarghya"
url: "https://www.acsu.buffalo.edu"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Anarghya Das<br/>
  Ph.D Candidate<br/>
  University at Buffalo

location: >
  <a href="https://www.google.com/maps/place/43.002942213328105,-78.78734210667226" target="_blank"><i class="fa fa-map-marker fa-1x"></i> 340 Davis Hall, Amherst, NY 14260</a>

contact: >
  <a href="mailto:anarghya@buffalo.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Anarghya via email</a> <br/>
  <a href="https://matrix.to/#/@anarghya:matrix.org" target="_blank"><i class="fa fa-comment fa-1x"></i> Contact Anarghya via Matrix </a>
# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  # - name: talks
  # - name: research
  # - name: software
  # - name: team
  # - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Das
  first_name: [Anarghya]

  style: citesty
  locale: en

  source: /assets/
  bibliography: pubs.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
